[package]
name = "demo"
version = "0.1.0"
authors = ["PLR <51248199+plredmond@users.noreply.github.com>"]
edition = "2018"

include = [
    "src/lib.rs"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
